web:
  image: kamalzairig/drupal8
  volumes:
    - ./src/drupal:/var/www/html
    - ./conf/php:/usr/local/etc/php/conf.d
    - ./conf/ssmtp:/etc/ssmtp
  ports:
    - 80:80
  links:
    - db:mysql
db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: P@ssw0rd
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: P@ssw0rd
  volumes:
    - ./data/mysql:/var/lib/mysql
    - ./conf/mysql:/etc/mysql/conf.d
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:db
  ports:
    - 81:80
    
